# Generated by Django 6.0.3 on 2026-03-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('icone', models.CharField(default='💻', max_length=10)),
                ('niveau', models.IntegerField(default=80, help_text='Niveau de 0 à 100')),
                ('categorie', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('outil', 'Outils')], default='frontend', max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technologies', models.CharField(help_text='Ex: React, Node.js, MongoDB', max_length=200)),
                ('lien_github', models.URLField(blank=True, verbose_name='Lien GitHub')),
                ('lien_demo', models.URLField(blank=True, verbose_name='Lien Demo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projets/')),
                ('emoji', models.CharField(default='🚀', help_text="Emoji affiché si pas d'image", max_length=5)),
                ('en_vedette', models.BooleanField(default=False, verbose_name='Mettre en avant')),
                ('ordre', models.IntegerField(default=0)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['ordre', '-date_creation'],
            },
        ),
    ]
