# Generated by Django 6.0.3 on 2026-03-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='categorie',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('outil', 'Outils'), ('autre', 'Autres')], default='frontend', max_length=20),
        ),
        migrations.AlterField(
            model_name='competence',
            name='icone',
            field=models.CharField(default='💻', max_length=100),
        ),
    ]
